name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 10.0.2
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml

      - name: package
        run: |
          mv fame-lib.jar fame.jar

      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: 'continuous'
          token: ${{ secrets.GITHUB_TOKEN }}
          files: fame.jar
